---
#==============================================================================+
# Description : Playbook to configure iptables for freeIPA server 
#
# Website     : https://github.com/fubralimited/ansible-catn-freeipa
#
# (c) Copyright:
#               Fubra Limited
#               Manor Coach House
#               Church Hill
#               Aldershot
#               Hampshire
#               GU12 4RQ
#               UK
#               http://www.fubra.com
#               support@fubra.com
#
# License:
#    Copyright (C) 2012-2013 Fubra Limited
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#==============================================================================+

- name: Apply DNS/TCP iptables rule
  command: lokkit -p 53:tcp
- name: Apply DNS/UDP iptables rule
  command: lokkit -p 53:udp
- name: Apply HTTP/TCP iptables rule
  command: lokkit -p 80:tcp
- name: Apply Kerberos—authentication system/TCP iptables rule
  command: lokkit -p 88:tcp
- name: Apply Kerberos—authentication system/UDP iptables rule
  command: lokkit -p 88:udp
- name: Apply NTP/UDP iptables rule
  command: lokkit -p 123:udp
- name: Apply LDAP/TCP iptables rule
  command: lokkit -p 389:tcp
- name: Apply HTTPS/TCP iptables rule
  command: lokkit -p 433:tcp 
- name: Apply Kerberos Change/Set password TCP iptables rule
  command: lokkit -p 464:tcp
- name: Apply Kerberos Change/Set password UDP iptables rule
  command: lokkit -p 464:udp
- name: Apply LDAPS/TCP iptables rule
  command: lokkit -p 636:tcp
- name: Apply DOGTAG/ TCP iptables rule
  command: lokkit -p 7389:tcp

